### ISSUE TITLE
Show loading indicator on message loading

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.ReactNative#1023]
Your Rocket.Chat Experimental app version: 0.15.0.8836
Your Rocket.Chat server version: 0.70.4
Device (or Simulator) you're running with: Xiaomi Mi 9

App currently won't indicates that it needs to download new messages to sync.

**Comment by reffu42** [comment]
Has there been any update or consideration of this feature? It can be confusing when you load a channel/room and the last message is from a while ago, since there's no way to tell if new messages are loading at all once the room is opened (unlike the channel list, which shows "Updating" in the top left while fetching updates)
