### ISSUE TITLE
No mention nor emoji dropdowns available when sharing a link 

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.ReactNative#1225]
- Your Rocket.Chat Experimental app version: 1.20.0.11408
- Your Rocket.Chat server 0.70.4
- Device (or Simulator) you're running with: Mi9 

When user is sharing a link via share extension and tries to mention or add emoji, he needs to write it manually rather than select it from the list.

**Comment by Infinity-Intellect** [comment]
Can I take up this issue?

**Comment by djorkaeffalexandre** [comment]
@Infinity-Intellect sure, go ahead.

**Comment by Infinity-Intellect** [comment]
I'm not able to reproduce this issue, could anyone walk me through the steps to get the issue?

**Comment by djorkaeffalexandre** [comment]
1. Open the Share Extension to share something.
2. Try to type `@a` or `:a`.
3. Nothing happens.

It needs to have a similar behavior of our `MessageBox`.

**Comment by Infinity-Intellect** [comment]
Where can I find the 'Share Extension' is it an icon in the application?

**Comment by djorkaeffalexandre** [comment]
@Infinity-Intellect Share Extension is the way that you use to share files/text from other apps to our app.

### iOS
![Screen Shot 2020-03-02 at 16 10 09](https://user-images.githubusercontent.com/29778115/75708842-55aac880-5ca0-11ea-91d0-d63b349ab849.png)

### Android
![Screen Shot 2020-03-02 at 16 13 03](https://user-images.githubusercontent.com/29778115/75709037-b5a16f00-5ca0-11ea-828e-d70cdead466a.png)

**Comment by Infinity-Intellect** [comment]
@djorkaeffalexandre Could you have a look at the screenshots below and let me know if I have tried to reproduce it correctly? Because the text seems to be appearing for me, so I think I haven't reproduced it properly.

![Screenshot_20200303_004956](https://user-images.githubusercontent.com/49329642/75709722-3be1a380-5ce9-11ea-86d9-fcaad80d0c09.png)
![Screenshot_20200303_004940](https://user-images.githubusercontent.com/49329642/75709746-4603a200-5ce9-11ea-9836-84b0bcd8578a.png)
![Screenshot_20200303_004923](https://user-images.githubusercontent.com/49329642/75709764-4b60ec80-5ce9-11ea-844b-0728dbbc145d.png)
![Screenshot_20200303_004901](https://user-images.githubusercontent.com/49329642/75709783-5582eb00-5ce9-11ea-91e0-d43fcec5027d.png)

**Comment by Infinity-Intellect** [comment]
Okay, so what's expected is similar to what happens in whatsapp group wherein we type '@' and a list of members automatically show up, are we trying to achieve the same result here?

**Comment by djorkaeffalexandre** [comment]
@Infinity-Intellect, how you can see, when you type some command to the input on Share Extension, nothing happens, the idea is to show the options like the messageBox:

![Screen Shot 2020-03-03 at 16 26 01](https://user-images.githubusercontent.com/29778115/75811772-cc60c800-5d6b-11ea-96f4-a5ff0533a6d4.png)

![Screen Shot 2020-03-03 at 16 27 19](https://user-images.githubusercontent.com/29778115/75811817-e00c2e80-5d6b-11ea-8bc8-000ab8bdedc2.png)

![Screen Shot 2020-03-03 at 16 26 06](https://user-images.githubusercontent.com/29778115/75811776-ce2a8b80-5d6b-11ea-9def-28ec27022c76.png)

![Screen Shot 2020-03-03 at 16 27 23](https://user-images.githubusercontent.com/29778115/75811824-e4384c00-5d6b-11ea-8333-5139380898bb.png)
