### ISSUE TITLE
Release 1.20.0 on Google Play while latest github release is 1.19.0

### ISSUE THREAD

**Issue by Nirkus** [RocketChat/Rocket.Chat.ReactNative#1279]
- Your Rocket.Chat Experimental app version: 1.20.0.11895
- Your Rocket.Chat server version: n/a
- Device (or Simulator) you're running with: n/a

Hi,

Google Play store distributes release 1.20.0 since 2nd Oct 2019, while the latest release and tag within this github repo today (7th Oct 2019) is 1.19.0.
Isn't this the authoritative git repo for Rocket.Chat Experimental on Google Play?

https://play.google.com/store/apps/details?id=chat.rocket.reactnative
Changelog:
```
What's New
- BREAKING CHANGE: We migrated our local database and you'll have to login again
- [NEW] Jitsi integration (voice/video call support)
- [IMPROVEMENT] Changed local database
- [IMPROVEMENT] Use JoyPixels
- Update dependencies
- Lots of bugs fixed
```

Did someone "lose" their Play store credentials? :-/

**Comment by diegolmello** [comment]
@Nirkus We have experimental both on Google Play and App Store.
We used to set a release tag and then send the app to the stores, but Apple can reject our App and forcing us to release another tag.
We're now always making sure everything is approved before releasing on the repo and that's the case for this version.
1.20.0 is released on Google Play since Oct 2nd, but it was approved by Apple only yesterday.
I'm working on a release right now.
Cheers.

**Comment by Nirkus** [comment]
Thank you for the fast reponse.
Can't help it, but this sounds upside down to me.. :)
Couldn't you just push a non-release tag before releasing to app stores and push the release tag after everything is approved?

**Comment by diegolmello** [comment]
@Nirkus Np. Let's try that next time.
