### ISSUE TITLE
[BUG] In-app notification redirect does not pull in correct room header

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat.ReactNative#1396]
- Your Rocket.Chat Experimental app version: 1.22.0.12660
- Your Rocket.Chat server version: 2.2.0
- Device (or Simulator) you're running with: Note 10+ 5G

Clicking on the in-app notification when a user messages a channel will direct you to the channel, however, the channel header will be the user's name instead of the channel.

1. User sends a message to `#helpdesk`
2. In-app notification is shown
3. Click in-app notification
4. Room header will be `# username` instead of `#helpdesk`

**Comment by localguru** [comment]
I do see the same problem here. If you click on the notification, you are in the correct channel, but in the header the username of the sender is displayed instead of the channel name. If new messages are posted in the app, they will be displayed in the correct channel. So only the header is wrong. Still quite confusing.
