### ISSUE TITLE
Notification but no message

### ISSUE THREAD

**Issue by rvlta** [RocketChat/Rocket.Chat.ReactNative#1451]
- Your Rocket.Chat Experimental app version: 1.25.0.13048
- Your Rocket.Chat server version: 2.1.1
- Device (or Simulator) you're running with: Android 9

When the app is off, the notification popup with the message and when i run the app the message don't appear.
If the discussion continue messages appears but not the first one.
But If the app is running in background and a notification come, the last message appear with all lost messages of the discussion

### To Reproduce

step 1 : close the app
step 2 : wait a notification
step 3 : run the app (the message don't appear, sometime but few time the message can appear)
step 4 : talk to see messages appear but not the first one
step 5 : wait for put the application running in background or open another app without close Rocket.Chat
step 6 : wait a notification
step 7 : open the app => you can see all messages appearing

**Comment by diegolmello** [comment]
I couldn't reproduce.
Can you record a video or something?

**Comment by rvlta** [comment]
Oh ?!
Strange because i can reproduce it with other users. Perhaps it come from of the server config.
1) I get the same problem with Rocket.Chat.Android 4.1.0.2095 https://github.com/RocketChat/Rocket.Chat.Android/issues/2524

2) I don't get this problem with 1.13.0.7546 but i don't receive notifications => same with Rocket.Chat.Android 3.5.0(2074)

**Comment by diegolmello** [comment]
Can you reproduce it on https://open.rocket.chat?

**Comment by rvlta** [comment]
It seem to be worst : 
I don't receive notifications and step 7 don't occure

**Comment by rvlta** [comment]
I got this log :
`I20191211-14:09:14.151(0) server.js:212 Integrations ➔ Outgoing WebHook.debug Starting search for triggers for the room: Lw 
I20191211-14:09:14.152(0) server.js:212 Integrations ➔ Outgoing WebHook.debug Found 0 to iterate over and see if the match the event. 
I20191211-14:09:14.739(0) server.js:212 API ➔ debug POST: /api/v1/subscriptions.read `

But idon't find the file /api/vi.sbscriptions.read

**Comment by rvlta** [comment]
I get this log discussion where AAA (rocket.chat.reactive 1.13.0.7546) is communicated with BBB (rocket.chat.reactive 1.25.0.13048)
[LogRC.txt](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/3951378/LogRC.txt)

**Comment by diegolmello** [comment]
@rvlta It might be irrelevant to the error, but why are you using 1.13.0?

**Comment by rvlta** [comment]
I think the key is in the file LogRC.txt but i can't decrypt it
i use 1.13.0 because i receive all the message but not the notification So 1.25 give me notification and 1.13.0 messages.
To me it's not a matter but for newbe users it's complicated and they often don't want to use RC anymore

**Comment by diegolmello** [comment]
Reach me on https://open.rocket.chat. I'm `diego.mello`.
I don't understand why messages aren't showing up to you.
Let's try to simulate this.

**Comment by allytech** [comment]
I can confirm this happens on RC Server 2.3.2 on Ubuntu 18 with an NGINX proxy for both iOS and Android devices.  We use our RC Server for critical outage communications and since the react native update, most of our users experience this issue.  You will receive a lock screen (banner) notification of a message but when you go to the channel that banner message is missing.  Other messages later may or may not show up but if you miss the banner message it will never show up in the channel.  On the desktop and web app everything is fine.

**Comment by allytech** [comment]
RC Experimental App 4.2.0.13336 seems to have fixed the issue.  Our messages now show in push and the channel for both iOS and Android.  Thank you very much!

**Comment by djorkaeffalexandre** [comment]
Nice @allytech ! :) If it happens again, fell free to comment here or open another issue. Thanks!

**Comment by rvlta** [comment]
Nope it didn't fixe the issue to me...

**Comment by brittyazel** [comment]
I think I might have this issue. On one of my channels I was informed that there were new messages and it even showed a snippet of the message content on the channel list, but upon opening the channel there were no new messages at all. Strangely though, when I view the channel on the web client, I do see the messages. So it appears it is just the mobile app unable to load these missing messages for some reason

**Comment by allytech** [comment]
So we had this same exact issue with the 4.1 version of the rocket chat iOS and Android client.  We had this problem at scale and it was causing crazy miscommunications in the organization.  We found that you have to completely delete all rocket chat clients from the mobile device and look for the "Rocket.Chat Experimental" app in the app store and sign in again.  If it does not ask you to sign in to the app, this issue will continue.  When our crew deleted all of their apps and then used only the experimental 4.2.0.13336 with RC server 2.3.2 the issue has almost completely gone away.  We have a few Android stragglers that still have issues but the volume of complaints about this has pretty much gone away.  I am not a developer in any way, just someone that appreciates this project and want the best for it, so I cannot promise it will fix your issue.  But if we can all post our experience here it will help the people that can fix it find the root cause.

**Comment by brittyazel** [comment]
Interesting. I did as you said and the particular channel in which I had this issue is now refusing to load any messages. It just endlessly spins with no messages loading in. No other channels have this issue.

This channel is a private channel. I'm not sure if that makes a difference

**Comment by gusevmk** [comment]
Same problem, in channel messages are not loaded on mobile application (RocketChat Experimental iOS / RC server version - 2.1.6) . Trying logout/login  helps load messages.

**Comment by rockneverdies55** [comment]
Why even there isn't a way to manually enforce the app to refresh/load/fetch messages. There is obviously a problem with the app on loading messages from server. 

Sometime it starts not loading new messages while you're in the channel but you get push notifications so you know there is something new, sometimes going back to chat list view and coming back to channel triggers re - load (sometimes not), sometimes totally closing and re-opening the app works, and sometimes it takes a very long time until you win this fight for seeing the new messages in your channel screen.

I don't know maybe simply adding pull-to-refresh kind of feature in channel window would be useful. That way if I'm not sure if the content is stale or fresh, i can trigger the fetch myself manually.

**Comment by diegolmello** [comment]
@rockneverdies55 We do have pull to refresh. Make sure you're up-to-date on the stores.

**Comment by QoobIY** [comment]
I have the same problem on both versions of Rocket (regular and experimental)

[Video](https://srv-file8.gofile.io/download/8msujX/video_2020-04-28_23-30-22.mp4)

**Comment by diegolmello** [comment]
@QoobIY `You are not authorized to download this file.`

**Comment by QoobIY** [comment]
upd:

**Comment by QoobIY** [comment]
@diegolmello 
We did as indicated here and the problem went away.
#1626 https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1626#issuecomment-582371373
