### ISSUE TITLE
[BUG] Share Extension sometimes doesn't load image and sends empty msg

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#1645]
- Your Rocket.Chat Experimental app version: 4.4.0
- Your Rocket.Chat server version: 2.5.0
- Device (or Simulator) you're running with: Samsung s10e Android 10

I couldn't reproduce it every time, but it happened 20% of the time here.
Trying to share a screenshot from gallery causes this:
<img src="https://user-images.githubusercontent.com/804994/73544209-6fde5600-4417-11ea-84e7-93830c68a3cc.png" width="350" />

The app tried to load the image, but something happened.
Maybe we should show an error on these cases (or load it differently)

**Comment by Prateek93a** [comment]
@diegolmello When this happens, if You press `Send`, does the attachment still get sent to recipient ?

**Comment by diegolmello** [comment]
Nope. An empty message is sent.

**Comment by Prateek93a** [comment]
I think maybe `fileInfo` must be null, hence nothing is displayed on the above shown screen. I could not reproduce the issue, so I explicitly set `fileInfo` to null, and got the above empty screen when sharing an image. When I pressed `Send`, it loaded for a while and then the app closed. When I checked the channel, there was nothing there. But  You also mentioned  an empty message was sent, so I will try to reproduce that.

**Comment by cprice-kgi** [comment]
is there a way to retro fit this fix into an older (4.9.0) version of the client? i'm observing the "blank" share screen (no image) like diego's above when sharing from gallery/photos on Android 10. if i type a caption to the file share, the caption will share, but not the file/image. this same action works fine and as expected using 4.9.0 on android 11.

the file structure was a bit different at this point in time (4.9.0) with a share/ subdirectory containing ShareActivity.java and ShareApplication.java.

Any ideas where to look in order to "fix" this empty file share issue on 4.9.0, Android 10?
