### ISSUE TITLE
Markdown rules aren't applied when there's a space inside rule token

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1763]
- Your Rocket.Chat Experimental app version: 4.4.0.99999999
- Your Rocket.Chat server version: 3.0.1 open.rocket.chat
- Device (or Simulator) you're running with: Android P

As the following gif shows, the markdown text is not rendered when there is space in between. On  webapp it is rendered. 
![ezgif com-crop (3)](https://user-images.githubusercontent.com/44807945/74928445-874da500-53ff-11ea-966d-5c12dcad665c.gif)

![Screenshot from 2020-02-19 18-20-46](https://user-images.githubusercontent.com/44807945/74928322-481f5400-53ff-11ea-94bd-b291584d2779.png)

**Comment by dantehemerson** [comment]
@Prateek93a  I think that markdown does not work that way, it does not accept blanks before and after asterisks, if you want to add space you must do so before `**`. Thus: ` **hello**` Otherwise Markdown interprets that you want to write that without transforming it.
I think this is a convention for Markdown.

**Comment by aKn1ghtOut** [comment]
Yeah, I looked it up a bit. It is definitely a convention for markdown, specifically the commonmark markdown specification. You can have a look at it over here: https://spec.commonmark.org/dingus/?text=*foo%20bar*%0A
This should probably be changed in the web version instead though. It would in fact be much better if all of Rocket Chat could follow a standard that is already very well out there.
