### ISSUE TITLE
Sort members in member list according to roles

### ISSUE THREAD

**Issue by Prateek93a** [RocketChat/Rocket.Chat.ReactNative#1806]
- Your Rocket.Chat Experimental app version: 4.5.0.99999999
- Your Rocket.Chat server version: 3.1.0-develop
- Device (or Simulator) you're running with: Android P Samsung Galaxy J6

Its a  suggestion issue. I think it might be useful if we display all members of a group sorted by roles, ie, in the all members list, not the online one, we show the members separated by roles but I am not sure if it's needed here.

**Comment by diegolmello** [comment]
IMO it's not a good UX. I'm going to let design team know about this and then I reopen if necessary.

**Comment by tjnull** [comment]
Hey @diegolmello do you happen to have any update from the design team on this? I am looking to set up a rocketchat instance and I think it would be great to have a way where we can sort members by the roles they have in the member list. Otherwise scrolling through the member list and looking for certain users can become tedious and time consuming. 

Discord and Slack have a feature that is similar and I think this would be a great feature for RocketChat to have. Unless you have any work around or an alternate way to sort members I would like to know. 

Thanks!
