### ISSUE TITLE
Mobile uploads: names of files are not saved if written in non-latin alphabet (Russian, Arabic, Chinese)

### ISSUE THREAD

**Issue by mar-v** [RocketChat/Rocket.Chat.ReactNative#1952]
- Your Rocket.Chat app version: 4.5.2.2110 (beta)
- Your Rocket.Chat server version: 3.1.0
- Device (or Simulator) you're running with: HT 70

Steps to reproduce:

1. Open the app, any room.
2. Click on add files button, select from library, change the name to anything containing Cyrillic, Arabic or Chinese characters (probably other non-latin as well, I only tested with these three)
3. Send the file. 
4. Check the file name in the web client. It will be either empty or containing universal characters if they were put in the initial fine name. 

![Filename](https://user-images.githubusercontent.com/47217833/77770870-994de380-704e-11ea-9bcb-4e82a3e7bbf2.png)

<img width="389" alt="Screenshot 2020-03-27 at 17 03 20" src="https://user-images.githubusercontent.com/47217833/77770988-c4d0ce00-704e-11ea-86e5-f887519e2ebc.png">

Expected behaviour: the file name should be reflected correctly no matter what language it's written in.

**Comment by ozata** [comment]
It works on my system. I reproduced a similar bug, though. When I send a photo with russian letters it looks okay on the mobile and web app,
but when I send with arabic letters it only shows on web app, does not show on mobile.

<img width="292" alt="1" src="https://user-images.githubusercontent.com/33320778/77829546-c2946f80-7133-11ea-920d-4cc35bf929e0.png">
<img width="477" alt="2" src="https://user-images.githubusercontent.com/33320778/77829551-c9bb7d80-7133-11ea-9323-4d91fad5adca.png">
<img width="423" alt="3" src="https://user-images.githubusercontent.com/33320778/77829556-ce803180-7133-11ea-883e-6df7dae326ff.png">
<img width="290" alt="4" src="https://user-images.githubusercontent.com/33320778/77829574-e952a600-7133-11ea-9529-fdbeccb6fb8b.png">

**Comment by shash137** [comment]
The bug is there for for both web as well as app client, I reproduce the bug and I tried file name in Russian, Arabic and Spanish language but after sending there was no name, except spanish.

Russian language
![Screenshot_20200329-130001 1](https://user-images.githubusercontent.com/44723604/77843844-996cf100-71be-11ea-8d3e-32a6d930bdda.png)
I didn't get the name in my web client, and also was not there in app client
![Russian](https://user-images.githubusercontent.com/44723604/77843867-e18c1380-71be-11ea-899b-cdc41a640032.PNG)

Arabic language
![Screenshot_20200329-125916 1](https://user-images.githubusercontent.com/44723604/77843848-a38eef80-71be-11ea-8835-c4a5cbc2f8bb.png)
I didn't get the name in my web client, and also was not there in app client
![Arabic](https://user-images.githubusercontent.com/44723604/77843892-10a28500-71bf-11ea-88ea-5c1cf40f3c5c.PNG)

Spanish language
![Screenshot_20200329-125753 1](https://user-images.githubusercontent.com/44723604/77843854-aee21b00-71be-11ea-918c-11d97d2054a2.png)
But we are getting the output for Spanish language
![Spanish](https://user-images.githubusercontent.com/44723604/77843905-316ada80-71bf-11ea-8f24-ce028f2b1aaf.PNG)
