### ISSUE TITLE
Jitsi Meet selfhosted server with JWT auth wotking in Mobile RocketChat?

### ISSUE THREAD

**Issue by arpsyapathy** [RocketChat/Rocket.Chat.ReactNative#2092]
Hi all!

Jitsi Meet selfhosted server with JWT auth wotking in Mobile RocketChat?

When i try join to video call i have endless spinning loading wheel =(

**Comment by ankar84** [comment]
> Jitsi Meet selfhosted server with JWT auth wotking in Mobile RocketChat?

Yes, it does!
Try latest RN application, check Jitsi and RC JWT settings.

**Comment by gerroon** [comment]
I have Jitsi with JWT works with the desktop Rocket.Chat clients but not the Android clients. The Android client cant seem to be able to initiate video or audio chat.

**Comment by arpsyapathy** [comment]
@gerroon +1
I have the same problem! :(

**Comment by ankar84** [comment]
@arpsyapathy self hosted Jitsi server with 2 virtual host's - first with jtw authorization and second guest without authorization.
Call can be started only by authorized user, but guest can then join that call.

**Comment by gerroon** [comment]
Not sure how you made it work. Like I said, I can initiate video calls via selfhosted Jitsi on the desktop clients no problem, but the Android client cant do it in the same rooms. How would I debug this?

**Comment by ankar84** [comment]
Can you please post gif or video with problem? Where we can see issue and client version.

**Comment by gerroon** [comment]
I cant get a video of it, it happens really fast  It says "connecting to meeting" then a popup shows up with 2 buttons but I cant read what it says on the buttons because happens way too fast

Android 9, Havos Os
Rocket.Chat 4.7.0.2121 
Server version 3.2.1

How do I make sure I am using my own Jitsi versions?  Like I said I can start video chats on the desktop clients no problem

Here is how it is setup.

https://i.imgur.com/MPHRPU3.png

**Comment by djorkaeffalexandre** [comment]
@gerroon your SSL certificate is correctly configured at your jitsi-meet server?
Maybe it has some mismatch, check if the secure is showed by browser
![Screen Shot 2020-05-20 at 12 52 23](https://user-images.githubusercontent.com/29778115/82468056-c344e480-9a98-11ea-8abe-9185063f8b26.png)

**Comment by gerroon** [comment]
My SSL cert is fine because I can use Jitsi alright in the browsers, or Jitsi mobile or with its own desktop apps.  I am using the Jitsi Docker install and forwarding it with Apache

As I mentioned the Rocket.Chat desktop apps have no problem using the video chat which I set up with my own Jitsi instance using JWT.

**Comment by djorkaeffalexandre** [comment]
@gerroon can you test this at some iOS device?

**Comment by gerroon** [comment]
I will try it that is what the wifes are for. I will restart my server and upgrade Jitsi as well, in case it is a server issue. It sounds like this should work in theory.

**Comment by gerroon** [comment]
Ok , some progress. The main issue of not connecting to the server could be an issue  with my wifi, since my desktop client is connecting to the server over the wire.  I will mess with it later.

I can connect to it using LTE, I can initiate a video call however not much use. I seem to have 2 issues.

- When the other side starts a video call it is not show in the room on the Android app (using the Gplay version but I do not have Gplay on this device) I assume this must be a google messaging thing, although nothing is show even when I am in the room actively.

-  When I start a video call in the app, the call drops when the otherside joins the chat. What is weird is that it says "jitsi.org" on the video feed of the Desktop client but not on the android app video. Normally the RC desktop clients do not show any `jitsi.org` watermark on the video feed itself. Quite curious.

**Comment by arpsyapathy** [comment]
> @arpsyapathy self hosted Jitsi server with 2 virtual host's - first with jtw authorization and second guest without authorization.
> Call can be started only by authorized user, but guest can then join that call.

@ankar84 can you show me your prosody conf with virtual hosts?

**Comment by ankar84** [comment]
> @ankar84 can you show me your prosody conf with virtual hosts?

Sure https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1356#issuecomment-564379308
