### ISSUE TITLE
State not immediately updated when a message is pinned or starred

### ISSUE THREAD

**Issue by Fishbowler** [RocketChat/Rocket.Chat.ReactNative#2324]
- Your Rocket.Chat Experimental app version: 4.10.0 (develop)
- Your Rocket.Chat server version: 3.2.2
- Device (or Simulator) you're running with: Simulator - iOS 13.6 on iPhone 11 Pro

When you Pin a message, it's "pinned" state isn't immediately updated internally. 
Immediately reopening the Action Sheet for the message shows the option to Pin again.
Leaving it a second before opening the Action Sheet (or closing and reopening) shows Unpin as an option, but the unpinning suffers the same problem - if you immediately try to pin again, you'll only be offered Unpin.

This issue also exists for Star/Unstar.

_Apologies for oddly low speed GIF. That's some odd mov-to-gif conversion to satisfy the GitHub gods._

![PinState](https://user-images.githubusercontent.com/2117083/88072745-523fad00-cb6d-11ea-83fe-ebbab5dd4e55.gif)

**Comment by diegolmello** [comment]
We talked private and I didn't reply here.
Yeah, we need to do some optimistic UI.

Instead of waiting for the new data to be returned via stream, we can assume the call was made and update the local database immediately after the promise is resolved.

**Comment by imrishabh18** [comment]
@diegolmello Can I take up this issue? And It would be great if I can get some directions on how to approach to solve this issue 🙂

**Comment by djorkaeffalexandre** [comment]
@imrishabh18 read the comment above. The approach is based on Optimistic UI

**Comment by diegolmello** [comment]
Cool.
Let's take `pin` action as example (from the gif above).

This is were the action is triggered: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/containers/MessageActions/index.js#L207

It makes a [REST API request](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/e1c8b10765640335d27e03d05f8ac22368c2db40/app/lib/rocketchat.js#L676) and receives the update [via socket](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/subscriptions/room.js#L235), but it can take a while.

Instead of waiting for the socket to update the local db, we can do it when the REST API call is resolved.

**Comment by imrishabh18** [comment]
I have messaged you in private in Rocket chat itself. Hopefully, you can respond me over there about the issue.

**Comment by SanjaySargam** [comment]
Is this issue resolved ?
