### ISSUE TITLE
[i18n] Add Turkish

### ISSUE THREAD

**Issue by mustifanci** [RocketChat/Rocket.Chat.ReactNative#2355]
hi. rocket app moves to reach but i can't choose Turkish Language anymore. Dou ever work on support Turkish language. if you want i and some turkish people contribute for turkish language.

**Comment by diegolmello** [comment]
@mustifanci Hey!
We would be glad to add all languages to our app, but it depends more on the community than us, since it's a hard job to add and keep them on track.

Add all translations based on [this file](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/i18n/locales/en.js) to your language.
Add it to the list [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/views/LanguageView/index.js#L23) and [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/i18n/index.js#L17)

I can't wait to review your contribution.
Thanks! :)
