### ISSUE TITLE
Proposal: Detect "single-server" operation by the presence of the "server:" directive in app.json

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2508]
My whitelabeled version from the "single server" branch was refused by Apple due to the iPad bug in IOS 14 (Touching on "status" in the user settings crashes the app). This is already fixed in the dev branch, but there is no up-to-date single server and you can't transfer the changes by the github diffs as so many files has been changed and sections which are altered at the last single-server commit are just different or completely gone in the same files of the dev branch.

I'd propose to change the app in a way, that an existing "server:" entry in app.json switches the app automatically in single-mode, means the server is fixed and the server selection and option to add new servers are deactivated.

In that way anyone can use the dev or any other branches and tags for own whitelabeled apps, and you as the dev team do not need to create a single-server version with every new version.

**Comment by diegolmello** [comment]
I see your point and something like that could be done, I guess.
The issue here is because `single-server` branch is updated during the release process.
Right after we update the `master` branch, we update `single-server`.
During this update, we merge changes made on `develop`, change some code to make it work for one server, test everything and update docs.
This way we can ensure the branch is **stable** and everyone reading the docs is applying up-to-date docs on a position in time we know for sure it works.

That said, this iOS 14 image issue is a specific case.
Apple releasing a new version as a _surprise_ + 4.11 taking longer time than usual to land because of e2e encryption implementation made this trouble.

WDYT, @jacotec?

**Comment by jacotec** [comment]
@diegolmello I'm absolutely fine with this. This was maybe also a borderline case as 4.10 had a crash issue on the iPad @IOS14 which led my app to be refused. So I wanted to get something without the crash submitted as fast as possible, which was only the dev branch.

Hence my idea, of which I also thought it would help you to avoid merging all again for the single-server branch. If it would self-detect the use case by the "server:" directive you would not need additional merging and testing as the "stable" would be automatically the "stable" also for single-server ... Just an idea. Not sure how many time you need to spend each time to merge and test the singe-server, having all in common code would ease that each time ;-)

**Comment by diegolmello** [comment]
Yup, but there's also `google-services`, api keys, etc involved.
We'll leave it as it is for now, but I guess we can make it at least closer to develop branch.
Thanks.
