### ISSUE TITLE
Voice Messages - length not displayed and scrubber not responsive in IOS apps and Safari browser, Firefox gives fantasy lengths

### ISSUE THREAD

**Issue by jacotec** [RocketChat/Rocket.Chat.ReactNative#2586]
### Description:

In the IOS apps and the Safari browser, all voice messages are displayed with length 0:00, as a result of this the scrubber and playback progress is also not working. You can't jump to a particular point in the messages.

![image](https://user-images.githubusercontent.com/3321655/94693164-ab794900-0333-11eb-9608-6e94e1580c9c.png)

I'm listing this in the server repo as this is not bound to the mobile IOS app, it's also the case on Safari browser on the Mac.

Chrome is displaying the correct lengths:
![image](https://user-images.githubusercontent.com/3321655/94693559-29d5eb00-0334-11eb-88b2-2561e9d74397.png)

Firefox is displaying fantasy lengths:
![image](https://user-images.githubusercontent.com/3321655/94693657-46722300-0334-11eb-8039-b4a6f6a2ca3a.png)

### Steps to reproduce:

Just send or receive a voice messages and check the showed length against the real lengths.

### Expected behavior:

All Apps and browsers should show the correct length.

### Actual behavior:

See above, Safari and IOS Apps show 0:00 as length, Firefox shows fantasy length and only Chrome shows the correct length.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: Ubuntu server 20.04 LTS 5.4.0-48-generic
- Deployment Method: Manual (tar)
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: The issue appears in the IOS app, Firefox and Safari. Only Chrome and Android app are correct.
- Operating System: IOS 14.0.1, Mac OS Catalina, Windows 10

### Additional context

On my test server the IOS app shows lengths, but they are wrong (the display is much too long). The only difference in the setup to my production server is that the production uses FileSystem as attachment storage, the Test Server uses GridFS. ALl other versions and OS are fully identical.

**Comment by jacotec** [comment]
@gabriellsh I'm not sure if reactnative is the right place. Maybe you can work around in the app, but running in Safari on the iDevice gives exactly the same results as the app ... hence I've categorized it to the server.

Fact is - it's not only the client side. Changing the storage from file system to GridFS I'm getting some time display in the players. It's not correct, it's displaying a much longer time than the voice message has in fact ... but at least the scrubber is moving and the biggest issues seems to be gone (playback stops and playback loops).

Working around in the app does not mean it works in a browser. Uploading an MP3 from a PC (container) still shows a length of 0:00 using file system storage.

So, apart from calculating the right length in the app and in all browsers the second question is why it does not work at all when the file is stored in the file system and working "half" if it's stored in GridFS.

**Comment by gabriellsh** [comment]
Okay, so there might be 2 different issues in place.
I'll map out my observations, see if they match yours.

Using GridFS:
* Audios recorded in any browser
  * Are saved as mp3
  * Shows correct length in every device or browser
* Audios recorded on mobile app
  * Are saved as .aac
  * Lengths vary depending on browser (expected due to format), but are mostly correct in safari and iOS app.

Using FileSystem:
* Audios recorded in any browser:
  * Still saved as mp3
  * Chrome and firefox show correct timing
  * Safari desktop shows the audio as `Live Broadcast`
  * Chrome, Safari and mobile app in iOS show length of 0, but audios are still playable (Chrome and Safari substitute the length for "Live Broadcast" when played).
* Audios recorded on mobile app
  * Saved as .aac
  * Incorrect timing everywhere
  * Same behaviour for Safari desktop and iOS, and mobile app

I didn't find any issues in the audio playback, although lengths where utterly imprecise.

To me it seems that recording the file as .aac is still a problem of its own. But, using FileSystem confuses the browsers/app for some reason. Regarding that, I think we should still keep an issue on the ReactNative side so we can fix the .aac length bug. I'll research a little bit more and see what I find.

**Comment by jacotec** [comment]
@gabriellsh This matches really good with my observations, except:

"but audios are still playable"
"I didn't find any issues in the audio playback, although lengths where utterly imprecise."

The issue's I've described did not happen with every message. But I've seen these issues by myself, my wife and they have also been reported by others. This might appear with one out of dozens messages, but if it's either playback stopping somewhere "in the middle" before the voice messages ends in real, some could not be played at all.

I could not see this since I've temporary switched to GridFS storage (where I at least have "some" lengths, although they are always too long). I guess sometimes the player is worried by the 0:00 length, but this is random an can't be reproduced everytime.

**Comment by gabriellsh** [comment]
Thanks a lot for your help figuring this one out @jacotec. I still didn't get audios to fail playback, but I think once the length issue is resolved, this other one will too.

> I have no idea how they manage to display the length exactly to the second on each device ...

Maybe they use a fixed encoding size.

**Comment by jacotec** [comment]
@gabriellsh I just want to kindly ask if there is any fix at the horizon? ;-)

**Comment by jacotec** [comment]
Closed with #3373
