### ISSUE TITLE
Why react-native-notifications is still 2.1.7?

### ISSUE THREAD

**Issue by progressify** [RocketChat/Rocket.Chat.ReactNative#2674]
### Description:

Today I tried to customize some push notifications logic but I see react-native-notifications is still an old version. 
Is there a particular reason? 

### Environment Information:

- Rocket.Chat Server Version: latest 3.8
- Rocket.Chat App Version: latest 4.12
- Device Name: pixel 2xl
- OS Version: android 11

**Comment by diegolmello** [comment]
Hey, @progressify.
We tried upgrading sometime ago, but they were still working on v3 and there're lots of breaking changes.
In the meantime, we worked on lots of features that required a ton of work from our side, like e2e encryption.
Hopefully, we will find some time to work do it on the next months, but that's not a priority since push notifications are working as expected.
Are you willing to contribute?

**Comment by progressify** [comment]
I don't know if I have enough experience with ReactNative for contributions to this work.
I gave a quick look at the code dependencies of the push notifications in the project. 
If you or someone of the community can give me a quick panoramic of the operation that I must to accomplish I can give a try.

**Comment by diegolmello** [comment]
hmmm it's not going to work.
They changed a lot of things there and we have to do it carefully, but thank you.

**Comment by progressify** [comment]
sorry 
I must close this issue?

**Comment by diegolmello** [comment]
Np, I did it.
Thanks.
