### ISSUE TITLE
Some mobile hasn't any notification, error is that we need android_channel_id

### ISSUE THREAD

**Issue by metal3d** [RocketChat/Rocket.Chat.ReactNative#2706]
### Description:

Android 8+ version don't have some notifications

### Environment Information:

- Rocket.Chat Server Version: 3.6.1
- Rocket.Chat App Version: built by ourself (4.12.0.103)

### Steps to reproduce:

Wait for notification on Android devices...

### Expected behavior:

Having notifications

### Actual behavior:

Server logs says:

```
I20201211-14:57:51.775(0) Push ➔ debug For devices running Android 8.0 or later you are required to provide an android_channel_id. See https://github.com/raix/push/issues/341 for more info
```

### Additional context:

We build our own ReactNative application this repository, no code modification, only some design changes (colors, images...)

See: https://github.com/RocketChat/Rocket.Chat/issues/16974

**Comment by toshanmugaraj** [comment]
@metal3d  Try clearing the mobile cache, and then logout. Now login again to get notification.

**Comment by diegolmello** [comment]
I have an Android 10 here and it's working.
Is this still an issue?

**Comment by MOST2K2** [comment]
Here its an issue. Did you get the same log output after sending a  test push message from admin panel?
@diegolmello ?

**Comment by diegolmello** [comment]
Not really.
It worked locally and it works properly on our open server: https://open.rocket.chat
Can you try there and see if it's working on your device?

**Comment by MOST2K2** [comment]
> Not really.
> It worked locally and it works properly on our open server: https://open.rocket.chat
> Can you try there and see if it's working on your device?

Send me a test message, i have posted in #sandbox

**Comment by MOST2K2** [comment]
Tested with Yash Rajpal and push notifiations are working with official app on open.rocket.chat.
I have connected from my white lableling app to open.rocket.chat and its not working.
Same apk is working at my wife´s Samsung S8 with Android 9.
At my Samsung S10 with Android 10 i get no push notifications.

**Comment by diegolmello** [comment]
I have an S10 here and it works.

**Comment by MOST2K2** [comment]
Do you have fcm enabled?

**Comment by MOST2K2** [comment]
Rocket Chat Push Gateway is working. My own FCM not :-(

**Comment by deva-gopalani** [comment]
Hey Diego... i needed your help... i have cloned this repository and i have made a few tweaks (UI related) for my use case... i have added FCM to my version too... now when we run the debug version (play) everything works fine. I just wanted your help to know how i could go about generating a release version of the same apk so that my users could use it. 

Currently the app works on local host so what should i do so that others can also start using this app? It would be great if you could help out! @diegolmello

**Comment by diegolmello** [comment]
@deva-gopalani Hey. Nice to hear that!
Follow these docs https://reactnative.dev/docs/signed-apk-android

**Comment by deva-gopalani** [comment]
> @deva-gopalani Hey. Nice to hear that!
> Follow these docs https://reactnative.dev/docs/signed-apk-android

Thanks for your prompt response @diegolmello ! I would surely refer this for making the release apk. 

Another doubt which I had was that now my debug application is working on the localhost. How could I make it work in such a way that my users could use it from anywhere? Like what changes have to be done so that the application can talk with my remote server?
