### ISSUE TITLE
Cannot update to the latest version via google play store

### ISSUE THREAD

**Issue by hibobmaster** [RocketChat/Rocket.Chat.ReactNative#2735]
![Screenshot_20201222_204920_com.android.vending.jpg](https://user-images.githubusercontent.com/32976627/102890255-194a9200-4497-11eb-8c6c-94ebe76f48ad.jpg)

**Comment by diegolmello** [comment]
Rolling out 4.13.0.22100 right now with a fix.
https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2734

**Comment by bradroid** [comment]
@diegolmello Hi, I have the same issue as in screenshot, but with my whiteleabeled app. My issue started occurring after I incorporated #2734 fix into my app. 
The issue is that I cannot install my app from Play Store if Rocket.Chat is installed on the same device. This is because they have the same `sharedUserId` declared in the Manifest, so I'm getting:
`The application could not be installed: INSTALL_FAILED_SHARED_USER_INCOMPATIBLE`

I fixed this by just changing the value of `sharedUserId` for my app.
- consider adding this step to whitelabel documentation
- is it okay to just change `sharedUserId` to my package name value? Will that break anything else? What is `sharedUserId` used for?

**Comment by diegolmello** [comment]
`sharedUserId` key was used by the native Android app and couldn't be removed on the migration to this repo, because it's how Google Play works.
They require a complete uninstall when this key conflicts.

What might be happening to your app is that you uninstalled and installed your app when the issue was active, so the current `sharedUserId` might be null.
When you added the fix and released to Google Play, you tried to updated to a version containing the key again.
If this is the case, "undo the uninstall", by uninstalling again and the new key should be added.
