### ISSUE TITLE
[Bug] "Chat listed ordered by first massage instead of last massage" on android

### ISSUE THREAD

**Issue by niiiixd** [RocketChat/Rocket.Chat.ReactNative#2781]
### Description:

Android application shows the date of the first chat on the chat page instead of the last chat date. This is while the date on the web and Ubuntu show correctly. Also, if we open the chat, the date will be displayed correctly.

#### Additional information:

- I already this problem by using version 4.12.1 android app on my phone
- This happen for all android user use version 4.12.1

### Environment Information:

- Rocket.Chat Server Version: 3.7
- Rocket.Chat App Version: 4.13.1.22186
- Device Name: Android phone
- OS Version: Android 10

**Comment by diegolmello** [comment]
Thanks for reporting.
Do you have a reproducible example?

**Comment by jillemash** [comment]
Hi,

I subscribed to this issue because I'm also seeing this for a while.
As for the reproduction steps, I don't know if it will work, but I guess you could try:
( - use fresh server/client, new account/contact to interact with)
- ask a contact to send you some messages.
- wait for a couple of days
- ask the contact to send a new message
- look at the messages in general "chat" view, ordered by Activity

EXPECTED BEHAVIOR
A snippet of the last message is visible, and the date is correct (the date of the last message)

OBSERVERVED BEHAVIOR (if bug is reproduced)
A snippet of the last message is visible, but the date is older than the last message (probably the date of the first message).
And this date will never change, no matter how many new messages are received.
If the message is clicked upon to open the conversation view, the messages are all in place, with the dates properly associated with every message.
The issue only concerns the "chat" view. The date being incorrect messes up the ordering.

Hopes this helps, because this make the app barely usable (I can kindda workaround the issue by checking the "unread on top" option, but as soon as I click on it, my message gets lost in the older messages instead of staying at the top.

Thanks.

(My server is older than @niiiixd (I don't have control over it, because it is handled by my org), but my client is more recent.

Environment Information:
Rocket.Chat Server Version: 3.0.13
Rocket.Chat App Version: 4.13.1.22186
Device Name: Google Pixel 3a
OS Version: Android 11

**Comment by niiiixd** [comment]
![LastVer](https://user-images.githubusercontent.com/10945984/104920823-a6590c00-59ad-11eb-907e-206da86d50c9.jpeg)

This is the last version of android app.

![Rochat-12](https://user-images.githubusercontent.com/10945984/104920879-bc66cc80-59ad-11eb-8e49-fc5dc8393409.jpeg)

and the second photo is 4.12.1 android app

**Comment by diegolmello** [comment]
Hi.
What's `last version` for you?
We have 4.14.0 on Experimental app with a couple of fixes.
Can you try there?
Thanks.

**Comment by niiiixd** [comment]
I can't find 4.14.0  and the last version in google play is 4.13.1.22186

**Comment by diegolmello** [comment]
https://github.com/RocketChat/Rocket.Chat.ReactNative#download

**Comment by niiiixd** [comment]
4.14.0 on Experimental app have the same problem as 4.13.1.22186

**Comment by jacalben** [comment]
Same problem here with version 4.13.1.22189

**Comment by akoselek273** [comment]
iOS: 14.3
App version: 4.14.0.22470 (installed by TestFlight)
Server version: 3.3.0
Same problem

**Comment by diegolmello** [comment]
Ok.
Can someone send me a reproducible example?
On https://open.rocket.chat, if possible.
Thanks.

**Comment by diegolmello** [comment]
Also, have you tried Settings > Clear local server cache?
It refreshes the sync between mobile and server.

**Comment by akoselek273** [comment]
My problem is solved after upgrade the server to the latest version (3.10.4)

**Comment by jillemash** [comment]
Hi,

clearing cache didn't work for me.
I've created an account on https://open.rocket.chat. The pseudo is jillemash and the status mentions the bug id (2781).
So if you (@diegolmello, or anyone else) could send  me some messages, with some delay between them, I could check whether updating the server might work for me too.

JM

**Comment by diegolmello** [comment]
@jillemash can you try updating your server to 3.10.4?

**Comment by jillemash** [comment]
@diegolmello I cannot do this easily because it's a corporate server.
That's why I wanted to test first on the 'open' server since it's the only thing that changes, so if it does work I could ask them to update the server.
I'll try to ask someone to make this test, I'll keep you posted.

**Comment by jillemash** [comment]
Hi,
I've tested the updated server by creating a second account on open.rocket.chat with another e-mail address, and it worked (same client, new server).
So it may be the solution for me, I'll try to have the server updated.
I have another question, I managed to delete one of my account, but I'm not able to delete the other because I created it with google sign-in and to delete my account, I'm asked to give my password, which I don't know because I didn't choose any.
Is there a way to delete these kind of accounts?
Thanks.

**Comment by diegolmello** [comment]
> I have another question, I managed to delete one of my account, but I'm not able to delete the other because I created it with google sign-in. I'm asked to enter my username, I put the same username than the one that appears in my profile page, but a pop up menu reads "invalid username".

That's weird. Have you tried logging in with email instead?
Fill an issue on https://github.com/RocketChat/Rocket.Chat if needed (not related to this repo).

**Comment by niiiixd** [comment]
The problem was solved after upgrading server version to 3.11.0

**Comment by diegolmello** [comment]
@niiiixd Thanks for your feedback.
We're going to merge backwards compatibility anyway on #2934
