### ISSUE TITLE
App Crashes on Startup 

### ISSUE THREAD

**Issue by amoebav** [RocketChat/Rocket.Chat.ReactNative#2884]
### Environment Information:

- Rocket.Chat Server Version: 2.2.0
- Rocket.Chat App Version: 4.14.1
- Device Name: iphone 7
- OS Version: 14.4

### Steps to reproduce:

Tap Rocket.Chat icon app on home screen to open. App opens then immediately crashes.

### Expected behavior:

App to open

### Actual behavior:

Tap Rocket.Chat icon app on home screen to open. App opens then immediately crashes.

### Additional context:

I remember having this issue a long time ago.

**Comment by C1ean** [comment]
looks like similarly to  https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2870

**Comment by diegolmello** [comment]
We need detailed logs to start investigating the issue.
Is it from the store? Is it whitelabel? Are you logged in? etc

**Comment by stayif** [comment]
same problem，when I start the Android app, it crashes。



https://user-images.githubusercontent.com/7867389/108647967-f0756600-74f4-11eb-8f41-3409a94728dc.mp4

![Screenshot_2021-02-19-16-42-43-084_com android se](https://user-images.githubusercontent.com/7867389/108647979-fa976480-74f4-11eb-951f-053cd589c52f.jpg)
![Screenshot_2021-02-19-16-42-33-875_com android se](https://user-images.githubusercontent.com/7867389/108647980-fb2ffb00-74f4-11eb-86a4-eb5530db699d.jpg)
![Screenshot_2021-02-19-16-40-44-512_com miui secur](https://user-images.githubusercontent.com/7867389/108647981-fbc89180-74f4-11eb-8647-401697f6a468.jpg)

**Comment by diegolmello** [comment]
@stayif Do you have logs? https://developer.android.com/studio/debug/bug-report

**Comment by ThangPh96** [comment]
I have the same problem when checkout single-server branch and configuring following this guide https://docs.rocket.chat/guides/developer/mobile-apps/whitelabeling-mobile-apps#important.

**Comment by stayif** [comment]
> https://developer.android.com/studio/debug/bug-report

@diegolmello thanks for your help
[bug.txt.zip](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/6026443/bug.txt.zip)
[bug.txt.2.zip](https://github.com/RocketChat/Rocket.Chat.ReactNative/files/6026444/bug.txt.2.zip)

**Comment by ThangPh96** [comment]
iOS log:

RROR: BSG_KSCrashState.m (183): _Bool bsg_kscrashstate_i_loadState(BSG_KSCrash_State *const, const char *const): /Users/thangphan/Library/Developer/CoreSimulator/Devices/36ACFE90-F825-4D49-BD76-EA63C728137D/data/Containers/Data/Application/5EDFE41E-A554-4F55-AF39-C1B5C7F35B33/Library/Caches/KSCrashReports/WorkUp/WorkUp-CrashState.json: Could not load file: Error Domain=NSCocoaErrorDomain Code=260 "The file “WorkUp-CrashState.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/thangphan/Library/Developer/CoreSimulator/Devices/36ACFE90-F825-4D49-BD76-EA63C728137D/data/Containers/Data/Application/5EDFE41E-A554-4F55-AF39-C1B5C7F35B33/Library/Caches/KSCrashReports/WorkUp/WorkUp-CrashState.json, NSUnderlyingError=0x600002913150 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
WARN : BSG_KSCrashSentry.c (103): BSG_KSCrashType bsg_kscrashsentry_installWithContext(BSG_KSCrash_SentryContext *, BSG_KSCrashType, void (*)(void *)): KSCrash: App is running in a debugger. Only user reported events will be handled.
Fatal error: Failed to open the database. unable to open database file: file /Users/thangphan/Desktop/WorkingPlace/WorkUp/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/Database.swift, line 19

**Comment by ThangPh96** [comment]
@amoebav I resolved this issue on iOS by https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/1332. Pls try it.
