### ISSUE TITLE
Error react-native run-android

### ISSUE THREAD

**Issue by dead23angel** [RocketChat/Rocket.Chat.ReactNative#321]
I want to test on the emulator with android 7.1.1
I run emulator.
I run react-native run-android, there is an assembly and installation on the emulator, upon termination it tries to open Intent, but there is an error

```
BUILD SUCCESSFUL

Total time: 27.365 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Running adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (adb -s emulator-5554 shell am start -n chat.rocket.reactnative/chat.rocket.reactnative.MainActivity)...
Starting: Intent { cmp=chat.rocket.reactnative/.MainActivity }
Error type 3
Error: Activity class {chat.rocket.reactnative/chat.rocket.reactnative.MainActivity} does not exist.

```

**Comment by diegolmello** [comment]
Hi, @dead23angel.
This is a known error.
When running a debug build, we append `.debug` to our appId in order to have both debug and production versions of the app on the same device.
This way we don't have to uninstall versions from Google Play while working on a new feature.

The downside is that the app is not launched automatically after a debug build.
If you take a look at installed apps on your android, you'll see a `[DEVELOP] Rocket.Chat` version of the app.
That's the debug version :)

**Comment by dead23angel** [comment]
Hi, @diegolmello!
And what can I do to be able to run after the build, since I would like to have the ability to run automatically when locally developed.

**Comment by diegolmello** [comment]
@dead23angel The app is installed. The only difference is that it won't be opened automatically.
