### ISSUE TITLE
F-Droid builds not updating

### ISSUE THREAD

**Issue by mirabilos** [RocketChat/Rocket.Chat.ReactNative#3462]
The latest version is 4.12.1, see: https://f-droid.org/en/packages/chat.rocket.android/

**Comment by LukeLR** [comment]
As of today, Rocket.Chat has disappeared from the f-droid repository. Searching for it (https://search.f-droid.org/?q=rocket.chat&lang=de) still reveals a hit, but the icon is missing, and clicking it reveals a 404: https://f-droid.org/de/packages/chat.rocket.android

I have been using Rocket.Chat from f-droid so far, and I think I am not the only one. I'd expect there are at least several people in the Rocket.Chat community that are not using or trying to avoid Google. Is publishing to f-droid completely off the roadmap?

**Comment by TheAssassin** [comment]
I also miss the Rocket.Chat libre variant from F-Droid. I use about 4 different servers regularly, and I'd need mobile access to at least some of them.

I'm not sure it's off the roadmap. I think it has been too much work for the Rocket.Chat folks to maintain the F-Droid build, though, so they put that on ice for now.
I presume that they could not estimate the user base over there due to the lack of analytics. I can only guess they thought it would not be large enough to continue maintaining the build therefore. This is unfortunate, because I estimate there are thousands of users who used to use the app from F-Droid. Rocket.Chat is one of the most popular alternatives to proprietary platforms and used in many companies, FOSS projects, universities etc. (people who value free/open-source software).
The F-Droid folks, who obviously do a great job and surely have time constraints, have not been too helpful with the last merge request, which might have put off the maintainers of this repository.

Recently, I noticed that this app is indeed really difficult to compile. I did not manage to find any build instructions, so I opened #3582. My hope is that once these are published (and ideally verified automatically using some CI), third party packaging such as F-Droid's could be maintained by F-Droid. When they can just go to a page to look for instructions, updating the metadata in fdroiddata should be relatively quick. Even outsiders like us could then contribute fixes to make sure Rocket.Chat is distributed on F-Droid again.

**Comment by Flam3z** [comment]
I just checked f-droid and the app doesn't exist even when i click the package link referenced above.

**Comment by hilburger** [comment]
Hi everybody :)
Are there any news in this?

I have switched to LineageOS and won't install any apps anymore which used Google Services. 
I think there are more people like me and the number will grow.

**Comment by czadikem** [comment]
Yes I would love to see the fdroid app version come back

**Comment by tcaxle** [comment]
As would I! Bump!

**Comment by licaon-kter** [comment]
https://f-droid.org/en/packages/chat.rocket.android/

/close this
