### ISSUE TITLE
Can you revert to React Navigation?

### ISSUE THREAD

**Issue by masterbater** [RocketChat/Rocket.Chat.ReactNative#366]
Hi, it seems that you moved to React Native Navigation, I would say that there are much more user who used React Navigation and its the library facebook recommended. 
You might have to RNN because of its Push Notification library.  Hope you would revert back to react navigation. Cheers!

**Comment by diegolmello** [comment]
@masterbater We do too much JS work related to websocket events.
We moved away from React Navigation because it's a JS based lib and it was dropping frame rate.
The guys from React Navigation are doing a great job, but it wasn't working for us.

React Native Navigation is 100% native, so it's less work for UI.

There is tons of discussions about RN's navigations libs and I could point several pros and cons of each (performance, maintainability, etc).

**Comment by masterbater** [comment]
@diegolmello good work to all of you guys.
I see, i would like to add this to my current app then thats why i wanted to use react navigation, i will migrate my existing codebase this.
I've got an issue though, current develop branch push notifications are not working

**Comment by diegolmello** [comment]
@masterbater Ok, open an issue about this push notification problem.
It's is working fine using a custom server here.
Can you elaborate more?
