### ISSUE TITLE
[NEW] Group notifications by room

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#391]
- [ ] Group notifications by room
- [ ] Show room icon
- [ ] Reply from notification

**Comment by BenWildeman** [comment]
@diegolmello I've been playing around with notifications on this repo as a test bed for my own application, and I'm wondering if grouping of notifications is the way you actually want to go?

the reason I ask, is because grouping the notification by channel would make sense only if this was like an email application, but it's not. when tapping on the notification, it will send you to the same place, regardless of what notification you tapped on, aka, the channel in which it's in regards to.

you could however group them by host, which would make more sense, and then use a combination of inbox style/messaging style notifications for the rest, so you're minimising the notifications visible in the notification shade (and group). You'd only need to update the notification in which the channel is in regards to, instead of creating a whole new notification for each push sent.

**however** I do have them grouped as per this ticket which is as follows:
![screenshot_20190217-223612](https://user-images.githubusercontent.com/3674467/52920483-ce90e980-3304-11e9-965c-e139411c7512.jpg)

![screenshot_20190217-223619](https://user-images.githubusercontent.com/3674467/52920478-c3d65480-3304-11e9-8fc7-1530914a5e07.jpg)

**Comment by BenWildeman** [comment]
example of messaging style notification:
![screenshot_20190217-230404](https://user-images.githubusercontent.com/3674467/52920807-b1f6b080-3308-11e9-8d4b-9b9a9bd0cb6a.jpg)

**Comment by diegolmello** [comment]
Very nice, @BenWildeman!
Can you open a PR with your progress?
What about notification reply? Have you played with?

**Comment by diegolmello** [comment]
Hi, @BenWildeman!
Are you still working on this?

**Comment by BenWildeman** [comment]
short answer is no

**Comment by ggazzo** [comment]
> short answer is no

do you have any draft or working in progress? maybe we could continue from there ;), thx

**Comment by BenWildeman** [comment]
you know what, I don't have anything to do this weekend so I can get this sorted for you guys 🙂

**Comment by ggazzo** [comment]
really thanks ❤️
