### ISSUE TITLE
[single-server] When I follow notification - app stucks on loading messages

### ISSUE THREAD

**Issue by nekkitl** [RocketChat/Rocket.Chat.ReactNative#4360]
Hi!

### Description:

In our neighbourhoods we chat a lot and we found issue. When we get a lot massages and want to read them - we got limitless loading messages frame…
We try to debug via logs/wireshark and find in code why its not working well and why app stuck on this.

### Environment Information:

- Rocket.Chat Server Version: 4.6 - Docker
- Rocket.Chat App Version: 4.26 - Single-Server
- Device Name: iPhone 12 Pro Max / Google Pixel 6
- OS Version: iOS 15.5 (iOS 16beta3) / Android 12

### Steps to reproduce:

1. Somebody send u messages (we spam them to faster reproduce)
2. Get all notifies on device, then
3. follow notifications and get this issue (look screenshot)

### Actual behavior:

Stucks on this, but if we continue write something - we see behind this loader.
(we changed loader picture for fun)
![screenshot](https://user-images.githubusercontent.com/107915590/178701214-7fd1a632-fdc4-4a66-9d50-e525d7309d7e.png)

**Comment by diegolmello** [comment]
Yep, so the issue is where I sent you.
When you tap the push notification, the app redirects you to the room and tries to scroll to the message you've tapped.
Since you're receiving too many messages while it tries to scroll, the app gets lost.
The logic should have a timeout in case it doesn't find the message.
