### ISSUE TITLE
jitsi integration in mobile app buggy 

### ISSUE THREAD

**Issue by gpopesc** [RocketChat/Rocket.Chat.ReactNative#4406]
### Environment Information:

- Rocket.Chat Server Version: 5.0.1
- Rocket.Chat App Version: 3.9 
- Device Name: Huawei
- OS Version: Android 10

### Steps to reproduce:

1. After  server version 5 I had to install apps plugin for jitsi in order to use jitsi meeting. (before that it was the menu in settings)
2. in Rocket chat mobile I can open chat window and use it as it was designed.
3. but if accidentally sweep the windows in mobile, press somewhere else, the window disappear. If I try to open the link again from chat window, then I can see the previous active window in jitsi. in this moment the mobile client has 2 or 3 active windows and some must be kicked out by admin.(see capture)
![Screenshot_20220803_153318_com android server telecom_edit_283736709330](https://user-images.githubusercontent.com/11590919/182610253-82fc0b7d-2b8d-435f-81ca-53509d4bcfdd.jpg)

### Expected behavior:

Why don't you add an option in rocketchat to open jitsi links (generated by rocketchat) with external jitsi android app (https://play.google.com/store/apps/details?id=org.jitsi.meet&hl=en&gl=US) This app is designed by jitsi, has all options and it is very stable.

**Comment by diegolmello** [comment]
Thanks for your report!
We've been building the new Video Conf solution and the idea is to make Rocket.Chat provider agnostic, so we need to discuss opening a 3rd party app.
I'm going to bring your idea to the product team.

**Comment by ankar84** [comment]
Hello, @diegolmello 
This issue is related to https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/2749 or maybe even duplicate.
Jitsi SDK have a few bugs in RCRN app because it is too outdated right now.

> We've been building the new Video Conf solution and the idea is to make Rocket.Chat provider agnostic, so we need to discuss opening a 3rd party app.

We spoke about that with Gabriel and Christian on [July community call](https://www.youtube.com/watch?v=eLvKzV68Aqo). And idea was to support some providers in clients and give ability to users to run calls in 3rd party app like Jitsi Meet in that particular case.

Here is my thoughts.
1. Using 3rd party app for Video Conf will force users to install another app (big PROS)
2. Using 3rd party app for Video Conf will frees mobile team resources because no need to update provider libs (CONS)
3. Using 3rd party app for Video Conf will give users best call experience because of using native and up-to-date client (CONS)
4. How to implement 1-on-1 calls with ringing (like it is already implemented on Web client) with 3rd party app for Video Conf?
5. How to implement all other stuff like monitoring who participate in call (already implemented on Web client) with 3rd party app for Video Conf?

If mobile team can implement all calling routine (ringing in 1-on-1 calls, monitoring who participate in calls and other that implemented on Web client) on RCRN side and 3rd party app for Video Conf will only operate call itself, in that case using 3rd party app will be a **good solution** with only one (but pretty major CONS) requirement of another app on phone.

My opinion - continue of support of Jitsi SDK in RCRN app (with update once in a half of a year) it is a best option. With some ability to users to choose if they want to use 3rd party app anyway.

**Comment by diegolmello** [comment]
@ankar84 Thanks for your thoughts!

We've been actively working on the ringing feature and that's why we didn't update Jitsi.

After ringing working properly and we're sure the ringing would work properly, what's your view if we do this?
- remove the embed Jitsi app
- if Jitsi installed, open the app
- if not installed, open in a webview

As you said, maintaining Jitsi is very expensive in terms of resources and having the 3rd party + webview solution would keep it in sync.

> And idea was to support some providers in clients and give ability to users to run calls in 3rd party app like Jitsi Meet in that particular case.

Doing it the way I suggested to Jitsi would be good to reuse the business logic for all providers, as embedding all providers is not possible (and it would be a mess).

**Comment by ankar84** [comment]
> After ringing working properly and we're sure the ringing would work properly, what's your view if we do this?\n\nremove the embed Jitsi app\nif Jitsi installed, open the app\nif not installed, open in a webview

Work of Jitsi in a webview need to be tested heavily, and if that test will be successful, then you solution will be nice!
RCRN app will a bit lighter and users will get up-to-date Jitsi app experience.

**Comment by diegolmello** [comment]
Closing as duplicated
