### ISSUE TITLE
Avatar images doesn't refresh

### ISSUE THREAD

**Issue by skhizerabass** [RocketChat/Rocket.Chat.ReactNative#441]
Please can you test this app on Android devices. Avatar uploading doesn't work on android. I have installed the latest version from playstore but it is not uploading my avatar.

**Comment by diegolmello** [comment]
@skhizerabass It's a known bug.
Currently this is a limitation in the image caching lib we're using: see https://github.com/DylanVann/react-native-fast-image/issues/197#issuecomment-385333467

We're open to PRs or even to react-native-fast-image PR fixing this error.
I'll leave this issue open until it's fixed.

**Comment by skhizerabass** [comment]
I believe it never uploads the avatar on server. Because i never get any response from server Nor it changes even after uninstalling and reinstalling the app.
Can you look into this issue ?

**Comment by diegolmello** [comment]
@skhizerabass Sure. I'll take a look as soon as react-native-fast-image is fixed too.

**Comment by SteveUNSW** [comment]
Hey team,

Any updates on this? Avatar doesn't refresh and I can't change it to anything.

**Comment by saadqbal** [comment]
We can resolve this for the time being by setting priority to high on FastImage in Avatar.js


`FastImage
		style={[styles.avatar]}
		source={{
		uri,
		priority: FastImage.priority.high
		}}
/>`

**Comment by saadqbal** [comment]
@diegolmello our code is way too changed. Won't be possible for you to merge.

**Comment by AugustoAleGon** [comment]
The best way for me was to add a ts which is always different...

**Comment by diegolmello** [comment]
@AugustoAleGon Can you explain more or open a PR?

**Comment by FreewheelingLive** [comment]
I chose the easy way. Enter any number after the URL. Restart the app. Then the photo has been changed.

**Comment by mahal** [comment]
I did a deep investigation into the issue and would like to share following result:
RC-RN client does not reflect any changes to the Avatar. 

RC-RN client: 4.6.4.295 iOS, 4.6.4.2118 (Android)
RC server: 2.4.11

Things I tried and tested:

- Setting the Avatar thru API on server
- Setting the Avatar thru Admin-Panel on server
- Setting an external Avatar provider

The "Avatar cache time" is correctly reflected in the http-response of the Avatar, but the RC-RN client does not respect it. Also using the apps "Clear local server cache" will not refresh the avatar. 

So from my point of view, the component FastImage is used with `FastImage.cacheControl.immutable` - (Default) instead of `FastImage.cacheControl.web` (Use headers and follow normal caching procedure). 

As I'm not fluent in React, I really wouldn't know where to set `cacheControl`.
