### ISSUE TITLE
Giphy not showing

### ISSUE THREAD

**Issue by brunogain** [RocketChat/Rocket.Chat.ReactNative#467]
We are using:

https://github.com/FinndropStudios/GifRocket

Giphy shows as a blank image.

Rocket.Chat.Android app version:
1.3.2.4272

- Device model (or emulator) you're running with:
Huawei P9 lite Android 7.0

- Steps to reproduce:
1. Add a new message "!gif monkey"
2. The bot will answer with an animated gif, which appears in the Stable mobile app and using the web browser.
3. On RocketChatRN we see only a blank / white placeholder instead of an animated gif

**Comment by diegolmello** [comment]
@FaizanZahid Thanks, man! :)

**Comment by FaizanZahid** [comment]
@diegodorgam you are welcome man, but after i tested it thoroughly , i cam across lots of crashing, each time i do some action, it crashes.

So for now we have decided to go with the android native kotlin app because it crashes less and has less bugs.

though we r keen in looking for react native development as your dreams are very promising and we cant wait to see the audio and video calls feature live and hence rocket chat will beat slack, whatsapp one day!!!

Crashes whenever i try to search a new user and send him msg for first time, it crashes the app. When i open app again, my msg gets sent, but why is app crashing? I have reported this bug report many times using the Google crash report troubleshooter.
Crashing when i select files, then try to record an audio message from my phones own sound recorder.
Sometimes when i open a DM with a new user and write my msg, the send button doesnt appear, the plus icon for files keeps on showing. SO i cant send msgs. also when i tap reuturn key on soft keyboard it goes to next line, so i cannot send the msg at all.
When i m in a DM with someone and another user in a general room is typing, i sometime get "is typing" msg from the other room in my room
