### ISSUE TITLE
Strange wording for reactions

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat.ReactNative#5018]
### Description:

If four or more users reacted to a message with the same emoji, when long pressing on the reaction emoji the app shows a text using some wording that has some room for improvement.

### Environment Information:

- Rocket.Chat Server Version: 6.1.1
- Rocket.Chat App Version: 4.36.0.38053
- Device Name: ELE-L29 (Huawei P30)
- OS Version: EMUI 12.0.0 (Android 11)

### Steps to reproduce:

You need at least four users. Steps 1 to 4 don't need to take place in the app.

1. Log in with the first user. Write a message and add a reaction emoji to it.
2. Log in with the second user. Add the same reaction emoji to the message.
3. Repeat step 2 with a third user.
4. Repeat step 2 with a fourth user.
5. In the app, long press on the reaction emoji.

### Expected behavior:

Proper wording is used.

### Actual behavior:

The wording in use has room for improvement:

![image](https://user-images.githubusercontent.com/404840/230788324-234ec50f-df9b-45dd-a9ab-8eaba8b29b75.png)

I would expect the text to be something like "test1, test2, test3 and 1 more" instead of "test1, test2, test3 and more 1".

When reacting with a fifth user, the wording looks like this:

![image](https://user-images.githubusercontent.com/404840/230788316-85f7ea56-19d8-48b9-8589-bad9a77205b1.png)

**Comment by diegolmello** [comment]
Hey @paulchen.
I didn't understand what's wrong with the current wording.
Is it because it should be `and 2 more` only or is there something else?

The idea for having that `All` tab is a summary of reactions, so it's always trimmed after a certain amount of reactions.
If the user wants to see everybody who reacted with a specific emoji, they can switch tabs to that emoji.
A full list of users is going to be displayed.

Can you elaborate on how we could improve this?
Thanks!

**Comment by paulchen** [comment]
> Is it because it should be `and 2 more` only or is there something else?

Yes.

You are right, I should have clarified that better.
