### ISSUE TITLE
Title not aligned in center

### ISSUE THREAD

**Issue by SanjaySargam** [RocketChat/Rocket.Chat.ReactNative#5464]
### Description:

In ThreadMessagesVIew and DiscussionView, when searching and then closing search then title `Threads` or `Discussions` is not aligned in center

### Environment Information:

- Rocket.Chat Server Version: 6.6.0
- Rocket.Chat App Version: 4.44.0+
- Device Name: Realme 9
- OS Version: Android

### Steps to reproduce:

1. Go to Threads or Discussions
2. Click on Search
3. Click on close icon

### Expected behavior:

The title must align in center

### Actual behavior:

The title does not align in center

### Additional context:

https://github.com/RocketChat/Rocket.Chat.ReactNative/assets/65113071/59bc4ad3-23d0-425a-8cdf-2e6b9321c506

**Comment by SanjaySargam** [comment]
If this is accepted then I am happy to work on it

**Comment by dexterco** [comment]
@SanjaySargam  Can i work on this issue?

**Comment by SanjaySargam** [comment]
@dexterco This issue is not yet accepted

**Comment by GleidsonDaniel** [comment]
This is an open source repo, so the community does not need to be approved about what it is doing, if you think that a feature could be interesting for the app, just do it.
And because it's open source, the interesting thing is to look at what's already being done and what can be improved. If we were to check every post from the community or every question about the app, we'd spend the whole day on this and wouldn't have time to focus on what it really is. necessary.
Another addendum is that there is no such thing as "I'm already working on it", as I said, it's an open source repo, anyone can do what they want, just because you're doing X doesn't mean your little friend can't do the same, the best solution is the accepted solution.
