### ISSUE TITLE
Inserting the new message received in Realm.

### ISSUE THREAD

**Issue by skhizerabass** [RocketChat/Rocket.Chat.ReactNative#585]
Can you point me to the code where we receive new message and we are inserting it into realm database. I want to put some checks for my application. If you can guide me on this it will be really . helpful.
Thanks in advance

**Comment by diegolmello** [comment]
Hi @skhizerabass.
When a message will be inserted to db, `buildMessage` is called to normalize it.
If you search for it, you'll find several places (load messages, sync messages, etc).
If you want just the stream in charge of receiving new messages, this is the one:
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/rocketchat.js#L190

I'm closing this because it's not an issue.
