### ISSUE TITLE
Leaving channels doesn't update on mobile

### ISSUE THREAD

**Issue by davidlougheed** [RocketChat/Rocket.Chat.ReactNative#624]
On the open.rocket.chat server, I left #general and #sandbox on the web app. These changes did not update on the latest TestFlight build (1.9.0.5693) on the iOS version of the react native app.

**Comment by diegolmello** [comment]
Thanks for opening @davidlougheed!
This is a known issue as you can see [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/helpers/mergeSubscriptionsRooms.js#L4)

We should do something similar to [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/helpers/mergeSubscriptionsRooms.js#L56)

**Comment by ebouJ** [comment]
@diegolmello can I take on this task?

**Comment by diegolmello** [comment]
@davidlougheed do you mind if @ebouJ takes this?

**Comment by davidlougheed** [comment]
@ebouJ @diegolmello go ahead, I’m busy with school right now and focusing on the markdown stuff anyway

**Comment by diegolmello** [comment]
@ebouJ Go ahead. Let me know if you need some help. Thanks.

**Comment by ebouJ** [comment]
Sure thanks

**Comment by ebouJ** [comment]
@diegolmello sorry, I was so busy with school I started working on this yesterday. I almost go mad because I was trying to debug and use console.log but they never appear on the chrome debugger I later found out that the project is using Reactotron and installed it. I'm getting comfortable with the codebase.  However, it seems like this is not an issue anymore. If I leave a channel on the web it updates on mobile. Can you confirm?
