### ISSUE TITLE
Bigger emojis in emojis only message

### ISSUE THREAD

**Issue by TheMythPT** [RocketChat/Rocket.Chat.ReactNative#725]
When we use just emojis in a message, they could be enlarged in a similar way as the web client does.

**Comment by diegolmello** [comment]
@TheMythPT Nice one! That can be achieved by doing a regex checking if there's only emojis and changing markdown to style it properly.
The regex must check emojis and custom emojis.

**Comment by real-player** [comment]
Can I work on this issue?

**Comment by diegolmello** [comment]
@real-player sure!

**Comment by reetp** [comment]
Adding myself to this because the size is far too big (testing on beta at the minute)

You just cannot use the same size on mobile that you do on a desktop. It takes up half the screen now. I want to read text, and the new size is extremely distracting.

It also turns the app from professional looking to a kids toy.

As you cannot control the size from the server (unfortunately) it either needs reverting to the previous more sensible size, or add a size selection option to the app.
