### ISSUE TITLE
DMs showing `Join` button

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#753]
- Your Rocket.Chat Experimental app version: 1.10.1

It's a rare case, but sometimes the app shows `Join` button on DMs.
`Join` button should appear only on public channels that aren't joined yet.

<img src="https://user-images.githubusercontent.com/804994/54751086-9d802f00-4bb8-11e9-995f-d82a02adcaea.png" width="350" />

**Comment by alleniver** [comment]
same problem!!

**Comment by diegolmello** [comment]
@alleniver Can you send more info?
I couldn't isolate the problem so far.

**Comment by alleniver** [comment]
The reason I have this problem here is that after frequent calls to connect and login operations, there is a certain probability that this problem will occur.

Because I use RC as a Modal, closing Modal will automatically disconnect, and then open chat that will automatically connect and login and create 1v1. This process will have a certain probability of this problem.

**Comment by alleniver** [comment]
Maybe it's also related to my separate management of Redux. I haven't seen much of it lately.

**Comment by diegolmello** [comment]
@alleniver 
> The reason I have this problem here is that after frequent calls to connect and login operations, there is a certain probability that this problem will occur.

I'll test this.

> Maybe it's also related to my separate management of Redux. I haven't seen much of it lately.

If you find something, let me know.
