### ISSUE TITLE
[FIX] Livechat is broken

### ISSUE THREAD

**Issue by diegolmello** [RocketChat/Rocket.Chat.ReactNative#808]

**Comment by jdaviescoates** [comment]
Yes.  Any plans to fix it? 

I note that in response to a recent (6 Feb 2020) negative review on Google Play that mentioned this issue Rocket.Chat responded saying "Livechat is not supported on mobile apps yet and we are planning to remove push messages for livechat." (not sure how much that'd help really - although I guess it would replace a horrible user experience with no experience at all)

It'd be really great for livechat to be working and fully integrated into the mobile app!

**Comment by diegolmello** [comment]
@jdaviescoates Hi. We implemented a beta for 4.4.0.
It has chatting support (we'll work on missing features soon), so the agents can receive push notifications and chat using the app.
It's planned to be released public February 20.
Cheers!

**Comment by jdaviescoates** [comment]
Great, thanks, looking forward to trying out the next version in a week's time! :-D

I actually already get push notifications from livechat (at least sometimes!) but unless the notification itself is clicked on there is no other way to browse to or get to the livechats.  

And even if the notifications are clicked on none of the previous messages (including the one in the push notification itself) are displayed.  Nor the guests name etc.

Hopefully all this will be fixed in the forthcoming beta on 20 Feb. Fingers and toes crossed :-D

**Comment by reetp** [comment]
Nothing in 4.6.x

Is this going to be added?

Difficult with so many people remote working and a lot now relying on mobile.

We don't get many live chats, but the ones we do get are often 'Out of Hours' when people are only on mobile and we then can't answer the livechat, despite getting an email notification.

That costs us customers and business - they don't want to hear you are having a day off - they go to someone else who has immediate answers.

**Comment by diegolmello** [comment]
Basic livechat (chatting) was fixed on #1674 and released on 4.6.
Visitor livechat page was implemented on #2004 and it's going to be released on 4.7 in a few weeks.
I'm closing.
