### ISSUE TITLE
[BUG] [IMPROVEMENT] Threads

### ISSUE THREAD

**Issue by IlarionHalushka** [RocketChat/Rocket.Chat.ReactNative#822]
@diegolmello nice feature, really useful one 👍 

### Bugs:
**1. Replies count doesn't update on Threads List Screen.** 
Steps to reproduce: 
- open Threads List Screen
- open Single Thread Screen
- send a new message
- go back to Threads List Screen

Expected: replies count of the message is incremented.
Actual: replies count of the message is not incremented.

**2. Draft message is shared between different Threads**
Steps to reproduce: 
- open Threads List Screen
- open Single Thread Screen
- type message '123' but don't send it
- go back to Threads List Screen
- open other Thread

Expected: draft message is not in input.
Actual: draft message is shared between Single Threads Screen.

**3. Reply on images, audio files doesn't work.**

**4. Reply to Thread with audio or image doesn't work**

**5. Threads List disappears in this channel:** https://open.rocket.chat/channel/ilariontest2
I have no idea why because haven't debugged it yet but I made the channel public for now.

### Improvements:
Nothing serious, just suggestions
1. Click on message which has replies should open Single Thread Screen. Now small button is used for this. Same should be done on Threads List Screen (but it's the same component Message).
2. Implement Scroll to refresh on Threads List Screen.
3. Remove or change position of date and time stamp on message on Threads List Screen (because on small screens it goes behind the screen).
4. When there are >= 100 (or >=10) replies to one message put 99+ (or 9+)

**To test: bell (mute) notifications of thread.**

- Your Rocket.Chat Experimental app version: 1.12.0.6971
- Your Rocket.Chat server version: open.rocket.chat
- Device (or Simulator) you're running with: Iphone SE

**Comment by diegolmello** [comment]
@IlarionHalushka Really nice catches there! Thanks for opening.
`Threads` is a "work in progress" yet, but I merged to keep other PRs in sync.
As you can notice, there's several workarounds to make `threads` and `threadMessages` in sync and all calls are made using DDP. That because [this PR](https://github.com/RocketChat/Rocket.Chat/pull/14045) didn't landed yet :)

I'll have to close this issue because there's several issues here and it'll be hard to track work.
Can you open issues for 1, 2 and 3-4?
5 is probably because of that workaround and we can talk about improvements on [#react-native](https://open.rocket.chat/channel/react-native)
