### ISSUE TITLE
Dissable notification not working

### ISSUE THREAD

**Issue by giterium** [RocketChat/Rocket.Chat.ReactNative#859]
- Your Rocket.Chat Experimental app version: 1.11.0.6782
- Your Rocket.Chat server version: 0.74.3
- Device (or Simulator) you're running with: iphone x 

Nothing happens when you click in the Disable notifications channel.

**Comment by diegolmello** [comment]
@giterium Just tested and it seems to work.
Maybe it's not working the way you think it should.
We're just toggling "Mobile" notifications (see image below).
We have plans to implement all "Notifications Preferences" in the future.
Let me know if it's working for you like I said in order to close this issue.

![image](https://user-images.githubusercontent.com/804994/56957899-01363a00-6b1f-11e9-8dfa-d47e1f132a9a.png)

**Comment by giterium** [comment]
Nothing happens to me by clicking Disable notifications in Direct Chat. Nothing opens. Just blink item. I don’t know what is going to happen there :)

**Comment by diegolmello** [comment]
@giterium are you checking on the web if it changes or complaining about UX?

**Comment by giterium** [comment]
you have a disable notification item there. If I click on it nothing happens. I told you about it. Each button performs some function. This button does nothing. I don't know what this button should do. maybe she should open a window with settings. how can i check?

**Comment by giterium** [comment]
if it turns off notifications just by clicking it means complaining about ux

**Comment by giterium** [comment]
In general, make at least the inscription changed or it is not clear

**Comment by diegolmello** [comment]
> We're just toggling "Mobile" notifications (see image below).
> <img src="https://user-images.githubusercontent.com/804994/56957899-01363a00-6b1f-11e9-8dfa-d47e1f132a9a.png" width="350" />

You're right about ux. It's terrible right now.
A simple toast would make it better.

**Comment by giterium** [comment]
Yes, thanks :)
